name: Trigger auto deployment for ca-oduotmrudnv7c

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ca-oduotmrudnv7c-AutoDeployTrigger-0c517ff0-7388-4d37-ad32-8f0d410a936e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CAODUOTMRUDNV7C_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CAODUOTMRUDNV7C_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CAODUOTMRUDNV7C_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: croduotmrudnv7c.azurecr.io
          registryUsername: ${{ secrets.CAODUOTMRUDNV7C_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAODUOTMRUDNV7C_REGISTRY_PASSWORD }}
          containerAppName: ca-oduotmrudnv7c
          resourceGroup: rg-copilot-demo
          imageToBuild: croduotmrudnv7c.azurecr.io/ca-oduotmrudnv7c:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


